# Generated by Django 3.2 on 2021-05-15 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 8, 23, 7, 769953, tzinfo=utc)),
        ),
    ]
