# Generated by Django 3.2 on 2021-05-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='message',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('p', 'publish'), ('d', 'draft'), ('i', 'investigation'), ('b', 'backed')], max_length=1),
        ),
    ]
