# Generated by Django 3.2 on 2021-05-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210517_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='message',
        ),
    ]
