# Generated by Django 3.2 on 2021-05-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='message',
            field=models.TextField(default=None),
        ),
    ]
