# Generated by Django 3.2 on 2021-05-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='message',
        ),
    ]
